sonar.projectKey=larnma
sonar.projectName=Larnma
sonar.projectVersion=0.0.0
sonar.host.url=http://localhost:9090

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/e2e/**,**/*.d.ts,**/types.ts,**/index.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/types.ts,**/index.ts,**/__tests__/**,**/app/**/layout.tsx,**/app/**/page.tsx
