import type { MenuItem } from './types'

export const MENU_CATALOG: MenuItem[] = [
  {
    id: 'kao-phat-gapraw',
    name: 'ข้าวผัดกะเพราไก่',
    price: 85,
    conditionsExcluded: [],
    allergensContained: [],
  },
  {
    id: 'tom-yam-kung',
    name: 'ต้มยำกุ้งน้ำใส',
    price: 120,
    conditionsExcluded: [],
    allergensContained: ['กุ้ง'],
  },
  {
    id: 'khao-tom-moo',
    name: 'ข้าวต้มหมู',
    price: 70,
    conditionsExcluded: [],
    allergensContained: ['หมู'],
  },
  {
    id: 'guay-jub',
    name: 'ก๋วยจั๊บญวน',
    price: 90,
    conditionsExcluded: [],
    allergensContained: [],
  },
  {
    id: 'pla-nueng-manaw',
    name: 'ปลานึ่งมะนาว',
    price: 140,
    conditionsExcluded: [],
    allergensContained: ['ปลา'],
  },
  {
    id: 'kanom-waan',
    name: 'ขนมหวาน',
    price: 45,
    conditionsExcluded: ['เบาหวาน'],
    allergensContained: [],
  },
  {
    id: 'nam-prik-pla-too',
    name: 'น้ำพริกปลาทู ผักสด',
    price: 95,
    conditionsExcluded: [],
    allergensContained: ['ปลา'],
  },
  {
    id: 'pad-see-ew',
    name: 'ผัดซีอิ๊วหมู',
    price: 80,
    conditionsExcluded: [],
    allergensContained: ['หมู', 'กลูเตน'],
  },
  {
    id: 'pad-thai-kung',
    name: 'ผัดไทยกุ้งสด',
    price: 110,
    conditionsExcluded: [],
    allergensContained: ['กุ้ง', 'ถั่ว'],
  },
  {
    id: 'khao-man-gai',
    name: 'ข้าวมันไก่',
    price: 65,
    conditionsExcluded: [],
    allergensContained: [],
  },
  {
    id: 'yam-woon-sen',
    name: 'ยำวุ้นเส้นทะเล',
    price: 100,
    conditionsExcluded: [],
    allergensContained: ['กุ้ง', 'ปลาหมึก'],
  },
  {
    id: 'tom-kha-gai',
    name: 'ต้มข่าไก่',
    price: 95,
    conditionsExcluded: [],
    allergensContained: [],
  },
  {
    id: 'pad-pak-ruam',
    name: 'ผัดผักรวม',
    price: 60,
    conditionsExcluded: [],
    allergensContained: [],
  },
  {
    id: 'khao-na-ped',
    name: 'ข้าวหน้าเป็ด',
    price: 90,
    conditionsExcluded: ['ความดันสูง'],
    allergensContained: [],
  },
  {
    id: 'rad-na-moo',
    name: 'ราดหน้าหมู',
    price: 75,
    conditionsExcluded: [],
    allergensContained: ['หมู', 'กลูเตน'],
  },
  {
    id: 'ice-cream',
    name: 'ไอศกรีมนม',
    price: 35,
    conditionsExcluded: ['เบาหวาน', 'ความดันสูง'],
    allergensContained: ['นม'],
  },
  {
    id: 'kung-tod-kratiem',
    name: 'กุ้งทอดกระเทียม',
    price: 130,
    conditionsExcluded: [],
    allergensContained: ['กุ้ง'],
  },
]
